server:
  port: 8005

spring:
  application:
    name: consul-provider-8005
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}