server:
  port: 7002

spring:
  application:
    name: enreka-7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  server:
    enable-self-preservation: false #关闭自我保护机制，心跳监控丢失，放弃provider
    eviction-interval-timer-in-ms: 10000 #清理事务间隔
