server:
  port: 80

spring:
  application:
    name: consumer-zk-80
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: true
        enabled: true
        instance-id: 1
